### ISSUE TITLE
java.io.IOException: Failed to bind to /47.111.105.219:8080

### ISSUE THREAD

**Issue by zhz20063096** [RWTH-i5-IDSG/steve#137]
While running mvn package i got following error:
[ERROR] 2019-05-19 17:03:01,311 de.rwth.idsg.steve.SteveProdStarter - Exception happened
java.io.IOException: Failed to bind to /127.0.0.1:8080
	at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:346) ~[jetty-server-9.4.17.v20190418.jar:9.4.17.v20190418]
	at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:308) ~[jetty-server-9.4.17.v20190418.jar:9.4.17.v20190418]
	at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80) ~[jetty-server-9.4.17.v20190418.jar:9.4.17.v20190418]
	at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:236) ~[jetty-server-9.4.17.v20190418.jar:9.4.17.v20190418]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) ~[jetty-util-9.4.17.v20190418.jar:9.4.17.v20190418]
	at org.eclipse.jetty.server.Server.doStart(Server.java:396) ~[jetty-server-9.4.17.v20190418.jar:9.4.17.v20190418]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) ~[jetty-util-9.4.17.v20190418.jar:9.4.17.v20190418]
	at de.rwth.idsg.steve.JettyServer.start(JettyServer.java:144) ~[steve.jar:?]
	at de.rwth.idsg.steve.SteveProdStarter.start(SteveProdStarter.java:37) ~[steve.jar:?]
	at de.rwth.idsg.steve.Application.start(Application.java:57) ~[steve.jar:?]
	at de.rwth.idsg.steve.Application.main(Application.java:46) ~[steve.jar:?]
Caused by: java.net.BindException: 无法指定被请求的地址
	at sun.nio.ch.Net.bind0(Native Method) ~[?:?]
	at sun.nio.ch.Net.bind(Net.java:461) ~[?:?]
	at sun.nio.ch.Net.bind(Net.java:453) ~[?:?]
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:227) ~[?:?]
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:80) ~[?:?]
	at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:342) ~[jetty-server-9.4.17.v20190418.jar:9.4.17.v20190418]
	... 10 more
[INFO ] 2019-05-19 17:03:01,324 org.eclipse.jetty.server.AbstractConnector - Stopped ServerConnector@a9f7cf8{HTTP/1.1,[http/1.1]}{47.111.105.219:8080}
[INFO ] 2019-05-19 17:03:01,324 org.eclipse.jetty.server.session - node0 Stopped scavenging
[INFO ] 2019-05-19 17:03:01,332 org.eclipse.jetty.server.handler.ContextHandler.steve - Destroying Spring FrameworkServlet 'spring-dispatcher'
[INFO ] 2019-05-19 17:03:01,344 com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown initiated...
[INFO ] 2019-05-19 17:03:01,354 com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown completed.
[INFO ] 2019-05-19 17:03:01,355 org.eclipse.jetty.server.handler.ContextHandler.steve - Closing Spring root WebApplicationContext
[INFO ] 2019-05-19 17:03:01,361 org.eclipse.jetty.server.handler.ContextHandler - Stopped o.e.j.w.WebAppContext@22dddb13{/steve,jar:file:/usr/local/src/steve/target/steve.jar!/webapp,UNAVAILABLE}

please suggest the issue

**Comment by zhz20063096** [comment]
I'll change the IP to 0.0.0.0, is OK
That's settled. Thank you.
