### ISSUE TITLE
Exception in thread "main" java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by kansal15** [RWTH-i5-IDSG/steve#238]
#### Checklist

- [ ] I checked other issues already, but found no answer/solution
- [ ] I checked the documentation and wiki, but found no answer/solution
- [ ] I am running the latest version and the issue still occurs
- [ ] I am sure that this issue is about SteVe (and not about the charging station software or something unrelated to SteVe)

#### Specifications
```
SteVe Version     : ... 3.4.0
Operating system  : ... Cent OS 7
JDK               : ...  openjdk 11.0.4 
Database          : ... 10.3.20-MariaDB
```

#### Expected Behavior

...

#### Actual Behavior

...

#### Steps to Reproduce the Problem

  1. ...
  2. ...
  3. ...

#### Additional context
Getting an error while trying to run the steve.jar file 

[root@CentOS steve-3.4.0]# java -jar target/steve.jar 
Exception in thread "main" java.lang.ExceptionInInitializerError
	at de.rwth.idsg.steve.Application.<init>(Application.java:40)
	at de.rwth.idsg.steve.Application.main(Application.java:63)
Caused by: java.lang.NullPointerException
	at de.rwth.idsg.steve.utils.PropertiesFileLoader.trim(PropertiesFileLoader.java:173)
	at de.rwth.idsg.steve.utils.PropertiesFileLoader.getOptionalString(PropertiesFileLoader.java:100)
	at de.rwth.idsg.steve.SteveConfiguration.<init>(SteveConfiguration.java:66)
	at de.rwth.idsg.steve.SteveConfiguration.<clinit>(SteveConfiguration.java:35)
	... 2 more

...

**Comment by goekay** [comment]
this has been fixed a few days ago. i just published a bugfix release 3.4.1. please use this one instead of 3.4.0
