### ISSUE TITLE
CentralSystemServer doesn't like empty websocket message

### ISSUE THREAD

**Issue by chuck-h** [RWTH-i5-IDSG/steve#66]
I have an OCPP1.6J charge point which consistently sends an empty websocket message after its pong message. This causes an error in the steve log after each ping.
```
[INFO ] 2018-05-15 09:26:52,345 de.rwth.idsg.steve.ocpp.ws.PingTask - [id=4faae375] Sending ping message
[INFO ] 2018-05-15 09:26:52,757 de.rwth.idsg.steve.ocpp.ws.ocpp16.Ocpp16WebSocketEndpoint - [chargeBoxId=Delta01, sessionId=4faae375] Received message: 
[ERROR] 2018-05-15 09:26:52,758 org.springframework.web.socket.adapter.jetty.JettyWebSocketHandlerAdapter - Closing session due to exception for JettyWebSocketSession[id=4faae375, uri=ws://192.168.1.133:8080/steve/websocket/CentralSystemService/Delta01]
de.rwth.idsg.steve.SteveException: Deserialization of incoming string failed: 
[...]
```
(more complete log extract below).

Functionally, the application recovers smoothly after closing and reopening the websocket.

Although there is no need for the charge point to send this empty message, I have read that this is a fairly common websocket "keep-alive" method and is generally considered benign.

It appears to me from the error log that this could be fixed by testing for a null incoming string before parsing it in ```steve/src/main/java/de/rwth/idsg/steve/ocpp/ws/pipeline/Deserializer.java```, but I do not understand the code very deeply.
```
    public void accept(CommunicationContext context) {
        try (JsonParser parser = mapper.getFactory().createParser(context.getIncomingString())) {
```
Here is the offending message sequence on the wire:   
![image](https://user-images.githubusercontent.com/2141014/40073555-007d6518-582c-11e8-882a-88d657fb93a4.png)  
![image](https://user-images.githubusercontent.com/2141014/40073300-51770ea2-582b-11e8-9e3e-5e8a57f5993e.png)

CentralSystemServer is 192.168.1.133, charge station is 192.168.1.128.

More complete steve error log extract:
```
[INFO ] 2018-05-15 09:26:52,345 de.rwth.idsg.steve.ocpp.ws.PingTask - [id=4faae375] Sending ping message
[INFO ] 2018-05-15 09:26:52,757 de.rwth.idsg.steve.ocpp.ws.ocpp16.Ocpp16WebSocketEndpoint - [chargeBoxId=Delta01, sessionId=4faae375] Received message: 
[ERROR] 2018-05-15 09:26:52,758 org.springframework.web.socket.adapter.jetty.JettyWebSocketHandlerAdapter - Closing session due to exception for JettyWebSocketSession[id=4faae375, uri=ws://192.168.1.133:8080/steve/websocket/CentralSystemService/Delta01]
de.rwth.idsg.steve.SteveException: Deserialization of incoming string failed: 
	at de.rwth.idsg.steve.ocpp.ws.pipeline.Deserializer.accept(Deserializer.java:75) ~[steve-3.0.1.jar:?]
	at de.rwth.idsg.steve.ocpp.ws.pipeline.IncomingPipeline.accept(IncomingPipeline.java:31) ~[steve-3.0.1.jar:?]
	at de.rwth.idsg.steve.ocpp.ws.AbstractWebSocketEndpoint.handleTextMessage(AbstractWebSocketEndpoint.java:90) ~[steve-3.0.1.jar:?]
	at de.rwth.idsg.steve.ocpp.ws.AbstractWebSocketEndpoint.handleMessage(AbstractWebSocketEndpoint.java:68) ~[steve-3.0.1.jar:?]
	at org.springframework.web.socket.adapter.jetty.JettyWebSocketHandlerAdapter.onWebSocketText(JettyWebSocketHandlerAdapter.java:83) ~[steve-3.0.1.jar:?]
	at sun.reflect.GeneratedMethodAccessor83.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_162]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_162]
	at org.eclipse.jetty.websocket.common.events.annotated.CallableMethod.call(CallableMethod.java:71) ~[steve-3.0.1.jar:?]
	at org.eclipse.jetty.websocket.common.events.annotated.OptionalSessionCallableMethod.call(OptionalSessionCallableMethod.java:72) ~[steve-3.0.1.jar:?]
	at org.eclipse.jetty.websocket.common.events.JettyAnnotatedEventDriver.onTextMessage(JettyAnnotatedEventDriver.java:234) ~[steve-3.0.1.jar:?]
	at org.eclipse.jetty.websocket.common.message.SimpleTextMessage.messageComplete(SimpleTextMessage.java:69) ~[steve-3.0.1.jar:?]
	at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.appendMessage(AbstractEventDriver.java:66) ~[steve-3.0.1.jar:?]
	at org.eclipse.jetty.websocket.common.events.JettyAnnotatedEventDriver.onTextFrame(JettyAnnotatedEventDriver.java:226) ~[steve-3.0.1.jar:?]
	at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.incomingFrame(AbstractEventDriver.java:162) ~[steve-3.0.1.jar:?]
	at org.eclipse.jetty.websocket.common.WebSocketSession.incomingFrame(WebSocketSession.java:476) ~[steve-3.0.1.jar:?]
	at org.eclipse.jetty.websocket.common.extensions.ExtensionStack.incomingFrame(ExtensionStack.java:220) ~[steve-3.0.1.jar:?]
	at org.eclipse.jetty.websocket.common.Parser.notifyFrame(Parser.java:220) ~[steve-3.0.1.jar:?]
	at org.eclipse.jetty.websocket.common.Parser.parse(Parser.java:245) ~[steve-3.0.1.jar:?]
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.readParse(AbstractWebSocketConnection.java:560) ~[steve-3.0.1.jar:?]
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillable(AbstractWebSocketConnection.java:391) ~[steve-3.0.1.jar:?]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281) ~[steve-3.0.1.jar:?]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102) ~[steve-3.0.1.jar:?]
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118) ~[steve-3.0.1.jar:?]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:319) ~[steve-3.0.1.jar:?]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:175) ~[steve-3.0.1.jar:?]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:133) ~[steve-3.0.1.jar:?]
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366) ~[steve-3.0.1.jar:?]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:754) ~[steve-3.0.1.jar:?]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:672) ~[steve-3.0.1.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
Caused by: com.fasterxml.jackson.core.JsonParseException: Current token (null) not numeric, can not use numeric value accessors
 at [Source: (String)""; line: 1, column: 1]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1804) ~[steve-3.0.1.jar:?]
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:668) ~[steve-3.0.1.jar:?]
	at com.fasterxml.jackson.core.base.ParserBase._parseNumericValue(ParserBase.java:781) ~[steve-3.0.1.jar:?]
	at com.fasterxml.jackson.core.base.ParserBase._parseIntValue(ParserBase.java:799) ~[steve-3.0.1.jar:?]
	at com.fasterxml.jackson.core.base.ParserBase.getIntValue(ParserBase.java:645) ~[steve-3.0.1.jar:?]
	at de.rwth.idsg.steve.ocpp.ws.pipeline.Deserializer.accept(Deserializer.java:52) ~[steve-3.0.1.jar:?]
	... 30 more
[WARN ] 2018-05-15 09:26:52,759 de.rwth.idsg.steve.ocpp.ws.ocpp16.Ocpp16WebSocketEndpoint - [id=4faae375] Connection was closed, status: CloseStatus[code=1011, reason=null]
[INFO ] 2018-05-15 09:26:53,637 de.rwth.idsg.steve.ocpp.ws.ocpp16.Ocpp16WebSocketEndpoint - New connection established: JettyWebSocketSession[id=7215b6a5, uri=ws://192.168.1.133:8080/steve/websocket/CentralSystemService/Delta01]
[INFO ] 2018-05-15 09:26:54,327 de.rwth.idsg.steve.ocpp.ws.ocpp16.Ocpp16WebSocketEndpoint - [chargeBoxId=Delta01, sessionId=7215b6a5] Received message: [2,"1526401612","Heartbeat",{}]
[INFO ] 2018-05-15 09:26:54,365 de.rwth.idsg.steve.ocpp.ws.pipeline.Sender - [chargeBoxId=Delta01, sessionId=7215b6a5] Sending message: [3,"1526401612",{"currentTime":"2018-05-15T16:26:54.327Z"}]
```

**Comment by goekay** [comment]
> Although there is no need for the charge point to send this empty message, I have read that this is a fairly common websocket "keep-alive" method and is generally considered benign.

the keep-alive strategy of websocket spec is, exchanging [ping-pong](https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API/Writing_WebSocket_servers#Pings_and_Pongs_The_Heartbeat_of_WebSockets). steve sends a ping and station responds with pong (as i see from your screenshot). so far, everything is correct.

what i cannot understand is: why does the station send an empty message for keep-alive (as you explain it). this is already handled with the ping-pong cycle.

having said that, i can modify the implementation in a way to let the empty messages slide to not cause a harm.
